spring:
  application:
    name: task-tracker-scheduler

---
spring:
  config:
    activate:
      on-profile: "!test"
    import: "configserver:http://config-server:8888"
  cloud:
    config:
      fail-fast: true
